### ISSUE TITLE
Instructions for creating a zarr dataset

### ISSUE THREAD

**Issue by mberg** [carbonplan/maps#10]
Congrats on this exciting release! 

Can you please provide instructions on how to use the ndpyramid to create a zarr file from a geotiff.  Examples of 2d, 3d and 4d would be ideal.  Thanks!

**Comment by jhamman** [comment]
Hi @mberg - thanks for your question! We can certainly help here. I opened #11 which should address your question.

**Comment by mberg** [comment]
The proposed Jupyter notebook sounds great. Thanks for the quick response and look forward to playing around with this more.

**Comment by jhamman** [comment]
@mberg - check out https://github.com/carbonplan/ndpyramid/blob/main/notebooks/demo.ipynb and let us know if you have any questions.

**Comment by jhamman** [comment]
I'll try to briefly explain what these two commands do. If we need to go much deeper, I suggest we open a new issue over on `ndpyramid`'s repo.

```python
dt = pyramid_reproject(ds, levels=6)
```

`levels`: the number of zoom levels to include in the pyramid. Level `0` corresponds to the coarsest level. Level 5 would be the finest zoom level.

The input to this function is an `Xarray.Dataset` with coordinates of `x` and `y` (longitude and latitude respectively). The output of this function is a new data structure called a `datatree.DataTree` (basically a dictionary of xarray.Datasets with keys 0, 1, 2, 3, 4, and 5 corresponding to each zoom level. The level `0` dimensions will be 128x128. Level `5` dimensions will be 4096x4096. 

------

```python
pyramid = pyramid_coarsen(ds, factors=[16, 8, 4, 3, 2, 1], dims=['lat', 'lon'], boundary='trim')
```

`pyramid_coarsen` is less relevant for this library since most applications require data to be reprojected to web mercator during the pyramid step. In brief, this function creates a similar `DataTree` but forgoes the reprojection step, instead progressively coarsening (averaging) the input data but the provided `factors`.
